plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gladimdim.omarchy.watchface'
    compileSdk 34

    defaultConfig {
        applicationId "com.gladimdim.omarchy.watchface"
        minSdk 33
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}
